### ISSUE TITLE
Unhandled server error

### ISSUE THREAD

**Issue by mrburke00** [Dfam-consortium/Dfam-API#1]
Hi,

I'm trying to get the API running for the first time, mainly querying a sequence. I keep getting an error 500. 

`response = requests.post("https://dfam.org/api/searches", data={'sequence': 'ATCG', 'cutoff': 'curated'})`
`print(response.json())`

**<Response [500]>
{'message': 'Unhandled server error.'}**

I just input a placeholder sequence above - I'm getting same results with my real sequence. 
Any help would be much appreciated. 

**EDIT**
Its because I did not include a species - Please add that species is required when using the curated cutoff. That took very long to figure out. Also its useful to know that the species has to match the one used by DFAM on the website. The 500 error code still persists if you say "horse" instead of "equus caballus" for example.

**Comment by rmhubley** [comment]
Sorry for the poor API documentation for this endpoint.  You are correct, the organism is necessary if you are using curated thresholds.  These thresholds are only applicable to only a small set of species for which this exhaustive analysis has been performed.  The endpoint also supports more general searching using the 'evalue' option.
